---
- hosts: all
  vars:
    - dest_user: "{{ lookup('env','NB_USER') | default('hallgato', true) }}"
    - dest_uid: "{{ lookup('env','NB_UID') | default(10000, true) }}"
  tasks:
    - name: enable dotnet package repos
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    - name: install required cli packages
      apt:
        pkg:
          - apt-transport-https
          - dotnet-sdk-3.1
          - python3-pip
          - nodejs
          - npm
          - locales
          - git
          - sudo
        update_cache: yes
    - name: upgrade distribution packages
      apt:
        upgrade: full
    - name: install required pip packages
      pip:
        executable: pip3
        name:
          - pipenv
    - name: setup system locale
      command:
        cmd: "{{ item }}"
      with_items:
        - "locale-gen hu_HU.UTF-8"
        - "update-locale LANG=hu_HU.UTF-8 LC_ALL=hu_HU.UTF-8"
    - name: "add default user {{ dest_user }}:{{ dest_uid }}"
      user:
        name: "{{ dest_user }}"
        home: "/home/{{ dest_user }}"
        comment: Hallgato
        password: $6$7uQS525NCE04TAQA$FS4oHPvK6j32ylaB9mN7ftpfDeKus0OhUGvq9GkxbLaFs/OYcgWmEr1oMOxprLhZUqxf0PAKQSinKfbdQ0INv0
        groups: sudo
        shell: /bin/bash
        uid: "{{ dest_uid }}"
    - name: fix /home permissions
      file:
          path: "/home/{{ dest_user }}"
          recurse: yes
          owner: "{{ dest_user }}"
    - name: setup jupyter
      command:
        cmd: "{{ item.cmd }}"
        creates: "{{ item.creates }}"
        chdir: "/home/{{ dest_user }}/oe-itseclabs/.build/"
      environment:
        LC_ALL: "C.UTF-8"
        LANG: "C.UTF-8"
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/{{ dest_user }}/.dotnet/tools"
      with_items:
        - {cmd: "/home/{{ dest_user }}/oe-itseclabs/.build/prep-system.sh", creates: "/home/{{ dest_user }}/oe-itseclabs/.build/.flag-prep-system-done"}
        - {cmd: "sudo -i -u {{ dest_user }} /home/{{ dest_user }}/oe-itseclabs/.build/prep-user.sh", creates: "/home/{{ dest_user }}/oe-itseclabs/.build/.flag-prep-user-done"}
    - name: copy files to /usr/local/bin
      copy:
        src: bin/
        dest: /usr/local/bin/
        owner: root
        mode: preserve
